# Generated by Django 5.2.10 on 2026-08-28 05:26

from django.db import migrations, models

def set_existing_users_verified(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.all().update(is_email_verified=True)

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_existing_users_verified, reverse_code=migrations.RunPython.noop),
    ]
