# Generated by Django 5.2.10 on 2026-01-23 05:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BalanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today, unique=True)),
                (
                    "cash_in_hand",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cash_in_account",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "debt_type",
                    models.CharField(
                        choices=[("TAKEN", "Taken"), ("GIVEN", "Given")], max_length=10
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("ACCOUNT", "Account")],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                ("is_cleared", models.BooleanField(default=False)),
                ("date", models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("ACCOUNT", "Account")],
                        max_length=10,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("EXPENSE", "Expense"),
                            ("INCOME", "Income"),
                            ("DEBT_TAKEN", "Debt Taken"),
                            ("DEBT_GIVEN", "Debt Given"),
                            ("CASH_WITHDRAWAL", "Cash Withdrawal"),
                            ("INVESTMENT", "Investment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FOOD", "Food"),
                            ("TRAVEL", "Travel"),
                            ("MEDICAL", "Medical"),
                            ("SHOPPING", "Shopping"),
                            ("RECHARGE", "Recharge / Internet"),
                            ("CHARITY", "Charity"),
                            ("LOAN", "Loan / Debt"),
                            ("INVESTMENT", "Investment"),
                            ("MISC", "Miscellaneous"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "related_debt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repayments",
                        to="finance.debt",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="debt",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debt_entry",
                to="finance.transaction",
            ),
        ),
    ]
