# Generated by Django 4.2.1 on 2026-02-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_category_alter_transaction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("EXPENSE", "Expense"),
                    ("INCOME", "Income"),
                    ("DEBT_TAKEN", "Debt Taken"),
                    ("DEBT_GIVEN", "Debt Given"),
                    ("CASH_WITHDRAWAL", "Cash Withdrawal"),
                    ("CASH_DEPOSIT", "Cash Deposit"),
                    ("INVESTMENT", "Investment"),
                ],
                max_length=20,
            ),
        ),
    ]
