# Generated by Django 4.2.1 on 2026-02-25 06:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("date", models.DateField(default=datetime.date.today)),
                ("is_completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="related_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="finance.event",
            ),
        ),
    ]
