# Generated by Django 4.2.1 on 2026-06-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_event_transaction_related_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("EXPENSE", "Expense"),
                    ("INCOME", "Income"),
                    ("DEBT_TAKEN", "Debt Taken"),
                    ("DEBT_GIVEN", "Debt Given"),
                    ("DEBT_TAKEN_RETURN", "Debt Taken Return"),
                    ("DEBT_GIVEN_RETURN", "Debt Given Return"),
                    ("CASH_WITHDRAWAL", "Cash Withdrawal"),
                    ("CASH_DEPOSIT", "Cash Deposit"),
                    ("INVESTMENT", "Investment"),
                ],
                max_length=20,
            ),
        ),
    ]
