# Generated by Django 5.2.10 on 2026-07-10 06:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_debt_description_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("purpose", models.TextField()),
                ("provider", models.CharField(max_length=100)),
                (
                    "initial_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("received_date", models.DateField(default=datetime.date.today)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("SETTLED", "Settled")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("settlement_date", models.DateField(blank=True, null=True)),
                (
                    "returned_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "additional_amount_required",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("settlement_notes", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="FundAddition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField(default=datetime.date.today)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additions",
                        to="finance.fund",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FundExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField(default=datetime.date.today)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="fund_attachments/"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.category",
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="finance.fund",
                    ),
                ),
            ],
        ),
    ]
