# Generated by Django 5.2.10 on 2026-07-10 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_fund_fundaddition_fundexpense"),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="payment_mode",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("ACCOUNT", "Account")],
                default="ACCOUNT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="settlement_extra_txn",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fund_settlement_extra",
                to="finance.transaction",
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="settlement_payment_mode",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("ACCOUNT", "Account")],
                default="ACCOUNT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="settlement_return_txn",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fund_settlement_return",
                to="finance.transaction",
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fund_initial_entry",
                to="finance.transaction",
            ),
        ),
        migrations.AddField(
            model_name="fundaddition",
            name="payment_mode",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("ACCOUNT", "Account")],
                default="ACCOUNT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="fundaddition",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fund_addition_entry",
                to="finance.transaction",
            ),
        ),
        migrations.AddField(
            model_name="fundexpense",
            name="payment_mode",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("ACCOUNT", "Account")],
                default="ACCOUNT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="fundexpense",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fund_expense_entry",
                to="finance.transaction",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="related_fund",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="account_transactions",
                to="finance.fund",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("EXPENSE", "Expense"),
                    ("INCOME", "Income"),
                    ("DEBT_TAKEN", "Debt Taken"),
                    ("DEBT_GIVEN", "Debt Given"),
                    ("DEBT_TAKEN_RETURN", "Debt Taken Return"),
                    ("DEBT_GIVEN_RETURN", "Debt Given Return"),
                    ("CASH_WITHDRAWAL", "Cash Withdrawal"),
                    ("CASH_DEPOSIT", "Cash Deposit"),
                    ("INVESTMENT", "Investment"),
                    ("FUND_MANAGEMENT_INC", "Fund Management (Incoming)"),
                    ("FUND_MANAGEMENT_DEC", "Fund Management (Outgoing)"),
                ],
                max_length=20,
            ),
        ),
    ]
