# Generated by Django 5.2.10 on 2026-08-05 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_balancesnapshot_profile_category_profile_and_more"),
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balancesnapshot",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name="balancesnapshot",
            unique_together={("date", "profile")},
        ),
    ]
