# Generated by Django 5.2.10 on 2026-08-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0012_alter_balancesnapshot_profile_alter_category_profile_and_more",
        ),
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "profile")},
        ),
        migrations.AlterUniqueTogether(
            name="event",
            unique_together={("name", "profile")},
        ),
        migrations.AlterUniqueTogether(
            name="ledger",
            unique_together={("name", "profile")},
        ),
    ]
