# Generated by Django 5.2.10 on 2026-08-07 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_alter_category_name_alter_event_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fund",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="fund",
            name="purpose",
        ),
        migrations.RemoveField(
            model_name="fundexpense",
            name="category",
        ),
        migrations.AddField(
            model_name="fund",
            name="ledger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="funds",
                to="finance.ledger",
            ),
        ),
    ]
