# Generated by Django 5.2.10 on 2026-08-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_remove_fund_provider_remove_fund_purpose_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fund",
            name="additional_amount_required",
        ),
        migrations.RemoveField(
            model_name="fund",
            name="returned_amount",
        ),
        migrations.RemoveField(
            model_name="fund",
            name="settlement_date",
        ),
        migrations.RemoveField(
            model_name="fund",
            name="settlement_extra_txn",
        ),
        migrations.RemoveField(
            model_name="fund",
            name="settlement_notes",
        ),
        migrations.RemoveField(
            model_name="fund",
            name="settlement_payment_mode",
        ),
        migrations.RemoveField(
            model_name="fund",
            name="settlement_return_txn",
        ),
        migrations.AlterField(
            model_name="fund",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("CLOSED", "Closed")],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
