# Generated by Django 4.2.1 on 2026-08-11 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0015_remove_fund_additional_amount_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="related_fund",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fund_debts",
                to="finance.fund",
            ),
        ),
    ]
