# Generated by Django 5.2.10 on 2026-08-20 08:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0016_debt_related_fund"),
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("EXPENSE", "Expense"),
                    ("INCOME", "Income"),
                    ("DEBT_TAKEN", "Debt Taken"),
                    ("DEBT_GIVEN", "Debt Given"),
                    ("DEBT_TAKEN_RETURN", "Debt Taken Return"),
                    ("DEBT_GIVEN_RETURN", "Debt Given Return"),
                    ("CASH_WITHDRAWAL", "Cash Withdrawal"),
                    ("CASH_DEPOSIT", "Cash Deposit"),
                    ("INVESTMENT", "Investment"),
                    ("INVESTMENT_RETURN", "Investment Return"),
                    ("FUND_MANAGEMENT_INC", "Fund Management (Incoming)"),
                    ("FUND_MANAGEMENT_DEC", "Fund Management (Outgoing)"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "investment_type",
                    models.CharField(
                        choices=[
                            ("GOLD", "Gold"),
                            ("STOCK", "Stock"),
                            ("MUTUAL_FUND", "Mutual Fund"),
                            ("BUSINESS", "Business"),
                            ("OTHER", "Other / Custom"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "custom_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("date", models.DateField(default=datetime.date.today)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="related_investment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="finance.investment",
            ),
        ),
    ]
