# Generated by Django 5.2.10 on 2026-08-20

from django.db import migrations

def migrate_legacy_investments(apps, schema_editor):
    Transaction = apps.get_model('finance', 'Transaction')
    Investment = apps.get_model('finance', 'Investment')
    
    # Get all INVESTMENT transactions that are not yet linked to any Investment model
    unlinked_txns = Transaction.objects.filter(
        transaction_type='INVESTMENT',
        related_investment__isnull=True
    )
    
    if not unlinked_txns.exists():
        return
        
    # Group transactions by profile
    profile_ids = unlinked_txns.values_list('profile_id', flat=True).distinct()
    
    for profile_id in profile_ids:
        # Create a default "Legacy Investment" for this profile
        legacy_investment = Investment.objects.create(
            profile_id=profile_id,
            name="Legacy Investment",
            investment_type="OTHER",
            custom_type="Legacy",
            description="Automatically created for legacy investment transactions.",
        )
        
        # Link all unlinked transactions of type INVESTMENT for this profile to the legacy investment
        Transaction.objects.filter(
            profile_id=profile_id,
            transaction_type='INVESTMENT',
            related_investment__isnull=True
        ).update(related_investment=legacy_investment)

def reverse_legacy_investments(apps, schema_editor):
    Transaction = apps.get_model('finance', 'Transaction')
    Investment = apps.get_model('finance', 'Investment')
    
    # Delete the legacy investments created by the data migration
    legacy_investments = Investment.objects.filter(
        name="Legacy Investment",
        investment_type="OTHER",
        custom_type="Legacy"
    )
    
    for invest in legacy_investments:
        # Clear relationship on transactions
        Transaction.objects.filter(related_investment=invest).update(related_investment=None)
        invest.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_alter_transaction_transaction_type_investment_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_investments, reverse_legacy_investments),
    ]
